### ISSUE TITLE
URFC-1: 组织（全）名，愿景（vision）和口号（slogan）

### ISSUE THREAD

**Issue by kenpusney** [unsafely/URFC#1]
比如，
- United Naive Security Agency of Future Evolvement
- United Naive & Simple Agency of Future Evolvement

**Comment by kenpusney** [comment]
@shellvon @uazw @RainySeattle @LYP951018 
赶快赶快出来聊天了。

**Comment by shellvon** [comment]
强行凑unsafe啊。
那s还是用Stupid吧

**Comment by kenpusney** [comment]
@shellvon 就是要强行凑啊。

我比较倾向Simple & Naive，但是Security显得更高大上。

**Comment by uazw** [comment]
Security吧

**Comment by kenpusney** [comment]
United / Unified 还是 Universal？

**Comment by kenpusney** [comment]
Slogan: make the world safe unsafely

**Comment by RainySeattle** [comment]
兹瓷  Naive & Simple

**Comment by kenpusney** [comment]
Resolved in #12
